In [1]:
print("to jest pierwszy notebook!")

to jest pierwszy notebook!


To jest ważne narzędzie do <span style="color:red; font-size:16pt">**projektowania**</span>  i wizualizacji modeli AI

In [5]:
a = 202
print(a)

202


In [6]:
b = 87
c = a+b
print(c)

289


In [10]:
lsztuk = 5

In [11]:
cena = "4.5"

In [13]:
lsztuk*float(cena)

22.5

In [14]:
import numpy as np

In [15]:
np.zeros(45)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [16]:
np.arange(1,113,2)

array([ 1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25,
 27, 29, 31, 33, 35, 37, 39, 41, 43, 45, 47, 49, 51,
 53, 55, 57, 59, 61, 63, 65, 67, 69, 71, 73, 75, 77,
 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99, 101, 103,
 105, 107, 109, 111])

In [17]:
m = np.array([[34,6],[8,24]])
m

array([[34, 6],
 [ 8, 24]])

In [21]:
a1 = np.arange(15).reshape(5,3)
a1

array([[ 0, 1, 2],
 [ 3, 4, 5],
 [ 6, 7, 8],
 [ 9, 10, 11],
 [12, 13, 14]])

In [22]:
b1 = np.arange(27).reshape(3,3,3)
b1

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])